### PR TITLE
Addded forgot Password

### LINKED ISSUE #91: [Feature Request]: Password Recovery Feature
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The password recovery feature allows users to reset their passwords securely if they forget them. This enhancement will involve creating a user-friendly interface where users can request a password reset link to their registered email addresses.

### Use Case

This feature will enhance user experience by providing a simple and efficient way for users to regain access to their accounts without requiring direct support intervention. For example, if a user forgets their password, they can easily request a reset link, enabling them to reset their password and regain access quickly.

### Benefits

Implementing this feature will:

Improve user experience by minimizing downtime due to forgotten passwords.
Reduce the workload on support teams by allowing users to handle password resets independently.
Enhance overall security by using secure password recovery processes (e.g., email verification).

### Add ScreenShots

Screenshot 2024-10-15 022439
Screenshot 2024-10-13 235803
Screenshot 2024-10-13 024658

https://github.com/user-attachments/assets/2b3f89b6-3ead-44b0-8265-6ea19e3ce13b

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by NK-Works**
### Description
A clear and concise description of what the PR does.
- This PR does the following:
  - Adds Forget Password Feature
  - Fixes #91
  - Updates forgot password, app

### Related Issues
Link any related issues using the format `Fixes #issue_number`. 
This helps to automatically close related issues when the PR is merged.
- Placeholder: "Fixes #91"

image
Make sure to add the env variables to access the feature

### Checklist
Make sure to check off all the items before submitting. Mark with [x] if done.
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I am working on this issue under GSSOC

### CODE REVIEW

**Comment by Soujanya2004** [comment]
@NK-Works conflicts in app.js

**Comment by NK-Works** [comment]
Resolved

**Comment by Soujanya2004** [comment]
@NK-Works

**Comment by NK-Works** [comment]
@Soujanya2004 now check all resolved...
i think this conflict cam due to merging of other reqs
and make sure to add the labels or else they wont be counted in the GSSoC

**Comment by Meetpidev** [comment]
@Soujanya2004 Its done.. you already accepted reset & update password..

**Comment by Soujanya2004** [comment]
@Meetpidev this feature sends mail to user to know their password

**Pull request merged**
