### PR TITLE
Fix UI Misalignment in Manage Listings from Admin Dashboard

### LINKED ISSUE #355: [Bug]: Manage listing  from admin dashboard  UI misalignment
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The Delete, Edit, and View buttons on the Listings Management Dashboard are not aligned or formatted consistently. The "Images" column also appears misaligned, affecting the overall look of the page.

### Expected behavior

Update the UI and all Edit, Delete, and View buttons/icons make visible properly.

### Add ScreenShots

Screenshot (245)

### On which device are you experiencing this bug?

_No response_

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by dipexplorer**
Fixes #355

This PR addresses issue #355 related to UI misalignment on the Manage Listings page of the Admin Dashboard. The alignment of the Delete, Edit, and View buttons, as well as the Images column, has been corrected to ensure a consistent and professional appearance.

### Changes
-  Made necessary CSS changes to enhance the overall responsiveness and look of the buttons and columns.
- remove normal table with bootstrap grid system.
- adding proper media queries.

### Testing Instructions
Detailed instructions on how to test the changes. Include any setup needed and specific test cases.
1. Pull this branch.
2. Run `npm install` to install dependencies.
3. Run `npm test` to execute the test suite.
4. Verify that ...

### Checklist

Screenshot (248)

Screenshot (249)

- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I am working on this issue under GSSOC

### CODE REVIEW

**Comment by Soujanya2004** [comment]
@dipexplorer screenshots are still uploading

**Comment by dipexplorer** [comment]
> @dipexplorer screenshots are still uploading

i am trying but not uploaded.

**Comment by Soujanya2004** [comment]
@dipexplorer yeh merged

**Comment by Soujanya2004** [comment]
> @Soujanya2004 ,
> 
> I've encountered an issue with uploading a video or screenshots when I raise issues or PR. I've tried multiple times, but it still isn't uploading, even though the file size is small. This problem has occurred many times, and each time it takes quite a while with no success.
> 
> Do you have any suggestions or workarounds for this?

i encountered same while uploading video, not for screenshots
try to clear your browser cache, cookies

**Pull request merged**
