### PR TITLE
Adding Password Field in DB

### LINKED ISSUE #444: [Bug]: Password not stored in DB
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Password is not stored in Database and main problem is how we can reset our password, or recover its password.

### Expected behavior

How we can uniquely identify is this email having this password.

### Add ScreenShots

user

### On which device are you experiencing this bug?

_No response_

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by harshbhar0629**
### Description
Now Database also have password field so that it can help to forgot password or recover email password.
- This PR does the following:
  - Fixes #444 
  - Close #444 

### Changes
List the detailed changes made in this PR.
- Fixed a bug in website which is not stored the password field in database.

### Screenshots (if applicable)
Adding password field in every creation of user.

db

admin

signupUser

### Checklist
Make sure to check off all the items before submitting. Mark with [x] if done.
- [X] I have performed a self-review of my code
- [X] My changes generate no new warnings
- [X] I am working on this issue under GSSOC

@Soujanya2004 Please review it and merge it with labels.

### CODE REVIEW

**Comment by Meetpidev** [comment]
password is already stored in hashed formate in DB..

**Comment by Soujanya2004** [comment]
@harshbhar0629 i want u to pull code and check once

**Comment by harshbhar0629** [comment]
> @harshbhar0629 i want u to pull code and check once

I also checked using postman:)

**Comment by Meetpidev** [comment]
system is also working fine without adding password field

**Comment by harshbhar0629** [comment]
SEE:)

dbPhoto

**Comment by harshbhar0629** [comment]
> system is also working fine without adding password field

system is working fine because there is no DB call at login time and how you will verify email?? if i'm creating account then how can i know my salt and hash????

**Comment by Meetpidev** [comment]
> > system is also working fine without adding password field
> 
> system is working fine because there is no DB call at login time and how you will verify email?? if i'm creating account then how can i know my salt and hash????

by your email.. and why do you want to know your salt and hash ? user dont interested to know it..

**Comment by Meetpidev** [comment]
you are storing pssswork as it is.. so anyone can hack it.. there is no need to store password.. as hashed passis storing

**Comment by harshbhar0629** [comment]
> Yeah i also know but there is another issue exist for this which is not created by me but created by someone now i will fix that issue:)
@Meetpidev see I will fix by another issue which is already exist

**Comment by harshbhar0629** [comment]
> > > Yeah i also know but there is another issue exist for this which is not created by me but created by someone now i will fix that issue:)
> > > @Meetpidev see I will fix by another issue which is already exist
> 
> dont understand what you are saying ...?

Brother ek issue phle s create hua h jo password ko hashed krana chahta h to m uss issue p work krra hu

**Comment by Meetpidev** [comment]
are par password toh already hased formate me store toh ho hi raha hai na...

**Comment by Meetpidev** [comment]
we can change and update password by this hased formate.. and that is DB is storing..

**Comment by Soujanya2004** [comment]
@harshbhar0629 @Meetpidev guys what is the issue can anyone tell properly
i have created signup in which the password entered by user is hashed and stored using passport-local
@harshbhar0629 what are u trying to change in this pr?

**Comment by Meetpidev** [comment]
@Soujanya2004 He is storing password as it is in DB.. but DB is already storing password in hased formate.. so i think its no need because we can change and update pssword by that hased formate..

**Comment by harshbhar0629** [comment]
> @harshbhar0629 @Meetpidev guys what is the issue can anyone tell properly i have created signup in which the password entered by user is hashed and stored using passport-local @harshbhar0629 what are u trying to change in this pr?

In User model no password field that's why i'm creating this PR.

**Pull request closed without merging**
