### PR TITLE
TOP_LISTING_FEATURE

### LINKED ISSUE #463: [Feature Request]:  TOP RATED/POPULAR LISTINGS..
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

WE SHOULD ADD  TOP RATED/POPULAR LISTINGS..

### Use Case

WE CAN FIND THE BEST LISTINGS..

### Benefits

WE CAN FIND THE BEST LISTINGS..

### Add ScreenShots

_No response_

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by Meetpidev**
### Description
A clear and concise description of what the PR does.
  - Updates features

### Related Issues
Fixes #463

### DEMO
https://github.com/user-attachments/assets/97c2349c-9dfb-48d3-98a4-2ff5b92182ea

### Checklist
Make sure to check off all the items before submitting. Mark with [x] if done.
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I am working on this issue under GSSOC

### CODE REVIEW

**Comment by Meetpidev** [comment]
@Soujanya2004 Review PR..

**Comment by Meetpidev** [comment]
@Soujanya2004  Rating >=4 is consider as a top listings

**Comment by Meetpidev** [comment]
@Soujanya2004 Let me know if navbar style is disturbed.. because as you can see in video i fix the style of navbar.. even though let me know if its not styled properly..

**Comment by Soujanya2004** [comment]
@Meetpidev conflicts
navbar hover effect let it be like before with light red color

**Comment by Meetpidev** [comment]
> @Meetpidev conflicts navbar hover effect let it be like before with light red color

its the same already.. i dont change it..

**Pull request closed without merging**
