### PR TITLE
FIX TOP-LISTING PAGE STYLING

### LINKED ISSUE #530: [Bug]: improve style for top property page
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

change spelling of top properties
listing card not aligned properly
text in dark mode not visible on card name price and on heading

### Expected behavior

change style accordingly

### Add ScreenShots

Screenshot (280)

### On which device are you experiencing this bug?

_No response_

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by Meetpidev**
### Description
- This PR does the following:
  - Updates LISTING

### Related Issues
Fixes #530 

### Changes
- Fixed a STYLING

### DEMO
https://github.com/user-attachments/assets/e21577b6-a581-4298-9392-b7f6fa36424f

### Checklist
- [X] I have performed a self-review of my code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] My changes generate no new warnings
- [X] I am working on this issue under GSSOC

### CODE REVIEW

**Comment by Meetpidev** [comment]
@Soujanya2004 Review PR..

**Comment by Meetpidev** [comment]
@Soujanya2004 Review PR..

**Comment by Meetpidev** [comment]
@Soujanya2004 Requested to please accept it with level-3 as it solved 3 problems and worked with styled..

**Comment by Meetpidev** [comment]
@Soujanya2004 can i sent PR of other issue that have not solved till 5 days ? i solved that all.. so that the all the issue are solved before afternoon...

**Comment by AKSHITHA-CHILUKA** [comment]
Please add labels and merge it soon @Soujanya2004

**Comment by Meetpidev** [comment]
@Soujanya2004 Its level-2 issue.. you gave level 2 on issue of the solution.. so requested to assign level 2

**Comment by Meetpidev** [comment]
@Soujanya2004 Requested to assing level 2 as you gave label level 2 on this issue...

**Comment by Meetpidev** [comment]
@Soujanya2004  ??

**Pull request merged**
