### PR TITLE
UI and Dark Mode Fixes (#221 & #222)

### LINKED ISSUE #221: [Bug]: dark mode not implemented properly
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

input box of email is not changed in dark mode

### Expected behavior

change color of input box

### Add ScreenShots

Screenshot (1)

### On which device are you experiencing this bug?

_No response_

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### LINKED ISSUE #222: [Bug]: change login/signup hover color
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

hover color is not matching the theme of website

### Expected behavior

change grey color to red (same as hover color on 'Airbnb your home' in navbar)

### Add ScreenShots

Screenshot (3)

### On which device are you experiencing this bug?

_No response_

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by dipexplorer**
Fixes #222: Change login/signup hover color
Fixes #221: Dark mode not implemented properly

This PR makes visual adjustments to the login/signup hover color and fixes the dark mode implementation for the email input box, aligning the site’s theme for a cohesive user experience.

### Changes Made:

- **Login/Signup Hover Color:** Updated the hover color for login and signup to match the theme by changing it from grey to red, aligning it with the 'Airbnb your home' link for a consistent look.
- **Dark Mode Email Input Fix:** Corrected the color of the email input box in dark mode to match the theme, ensuring it updates appropriately when dark mode is active.

### Screenshots (if applicable)

https://github.com/user-attachments/assets/b96d926f-cf5a-423a-a727-128fca2d5396

### Checklist
Make sure to check off all the items before submitting. Mark with [x] if done.
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I am working on this issue under GSSOC

### CODE REVIEW

**Comment by dipexplorer** [comment]
Hello @Soujanya2004 ,

I've addressed both issues (#221 and #222) within this pull request as they relate to theme consistency and dark mode implementation.

So please consider awarding points for both issues under GSSoC, as this PR addresses them thoroughly and ensures they are each resolved?

**Comment by Soujanya2004** [comment]
@dipexplorer raise individual pr

**Comment by dipexplorer** [comment]
> @dipexplorer raise individual pr

@Soujanya2004  merge it because changes are to small.

**Comment by Soujanya2004** [comment]
@dipexplorer it has conflicts

**Comment by dipexplorer** [comment]
> @dipexplorer it has conflicts
@Soujanya2004
 
Resolved the conflict.

**Pull request merged**
