### PR TITLE
Redesign whole index page

### LINKED ISSUE #238: [Feature Request]: Want to redesign the whole index page
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Currently your index page the all listing display format is not perfect. Means here unnecessary padding and spacing  are there. Also the description section is not properly displayed. It is the main reason that the extra space is accuird by the lists. 
Also the `Show more` button is not looking good also it's not appear for all lists, So it's not looking good at all.
abc

### Use Case

It supposed to be look like this
image

Where description is not displayed. Because there is `show in deails` option so i don't think there is any nee dto display the description in front page. By doing this it also look more visually appealing

### Benefits

_No response_

### Add ScreenShots

https://github.com/user-attachments/assets/1112b4ef-5955-418f-ad85-edbd8fc99c46

@Soujanya2004  Please assign me this task. I want to work on this.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by Suvadip-sana**
### Description
I redesign whole index page as you can see in the attached video.
Here I also add a logic that if the card titel too big. It show a [...] after the titel. That because all the card looks good and organized. You can chek it in the video.
I make it look perfect as much as I can. Hope you like it.

- This PR does the following:
  - Updates ... Index page

### Related Issues
Link any related issues using the format `Fixes #issue_number`. 
This helps to automatically close related issues when the PR is merged.
- Placeholder: "Fixes #238 "

### Screenshots (if applicable)
Add any screenshots that help explain or visualize the changes.

https://github.com/user-attachments/assets/dde7e5bd-3ea3-4efa-8348-67d97a4785ce

### Checklist
Make sure to check off all the items before submitting. Mark with [x] if done.
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I am working on this issue under GSSOC

### CODE REVIEW

**Comment by Suvadip-sana** [comment]
@Soujanya2004  Please check it. And marge it. Don't forget to add all the labels as per ISSUE #238

**Comment by Suvadip-sana** [comment]
image
image
Normal mode.

**Comment by Suvadip-sana** [comment]
@Soujanya2004 

As you can see I also make changes of toggle button for dark mode 
image

**Comment by Soujanya2004** [comment]
@Suvadip-sana yeh yeh i reviewed it , great job by the way

**Pull request merged**
