### PR TITLE
feat: 🎸 Add the Like listing feature

### LINKED ISSUE #335: [Feature Request]: add like the listing feature
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

user should be able to like any listing 
the like icon should be placed on each listing in both show listing (detail view of listing) and view listing (homepage) pages.

### Use Case

to specify popularity of any listing

### Benefits

_No response_

### Add ScreenShots

on the top right corner of each listing there should be like icon/ heart icon
Screenshot (247)
Screenshot (248)
bottom right of each listing

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by yashksaini-coder**
✅ **Closes**: #335

### Description
A clear and concise description of what the PR does.

This PR does the following:
- Adds a "like" feature to the listings on both the homepage and detail view.
- Updates the listing model to include a `likes` field to track the number of likes.
- Implements a controller function to handle the liking of listings.
- Modifies the views to display the like button and the current number of likes.

### Related Issues
Link any related issues using the format `Fixes #issue_number`.  
This helps to automatically close related issues when the PR is merged.

- Fixes #335 

### Changes
List of detailed changes made in this PR:
- Added a new feature to allow users to like listings.
- Refactored the listing model to include a `likes` field.
- Updated the listing controller to handle the like functionality.
- Modified the views (`index.ejs` and `show.ejs`) to include like buttons and display the number of likes.
- Updated the main application routes to include the new like functionality.

### Testing Instructions
Detailed instructions on how to test the changes. Include any setup needed and specific test cases.
1. Pull this branch.
2. Run `npm install` to install dependencies.
3. Run `npm test` to execute the test suite.
4. Verify that you can like a listing on both the homepage and detail view.
   - Check that the number of likes updates correctly after liking a listing.

### Screenshots (if applicable)
Add any screenshots that help explain or visualize the changes.
- [Insert screenshots here if applicable]

### Additional Context
Any additional context or information that reviewers should be aware of.

- This PR is based on the following user requirement to enhance user engagement by allowing them to like listings.

---

### Checklist
Make sure to check off all the items before submitting. Mark with `[x]` if done.

- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I am working on this issue under GSSOC

---

@Soujanya2004 Thank you for being patient, review this PR, and assign it to me with proper labels

### CODE REVIEW

**Comment by Soujanya2004** [comment]
@yashksaini-coder great job
Can u please add necessary screenshot or video

**Comment by yashksaini-coder** [comment]
> @yashksaini-coder great job
> Can u please add necessary screenshot or video

I couldn't as the dev failed due to mapbox token error

I worked on previewing the files one by one.

**Comment by Soujanya2004** [comment]
@yashksaini-coder one of other contributor is using same mapbox token without any issues
can u specify the issue

**Comment by yashksaini-coder** [comment]
> @yashksaini-coder one of other contributor is using same mapbox token without any issues can u specify the issue

image

I have shared it on discord too

**Comment by Soujanya2004** [comment]
> > @yashksaini-coder one of other contributor is using same mapbox token without any issues can u specify the issue
> 
> image
> 
> I have shared it on discord too

Can u paste the full error here

**Comment by Soujanya2004** [comment]
@yashksaini-coder discord is having issue sending messages so please text here

**Comment by Soujanya2004** [comment]
@yashksaini-coder can u tell at what point u got this error also

**Comment by yashksaini-coder** [comment]
> @yashksaini-coder discord is having issue sending messages so please text here

okh where can I obtain a free mapbox token

**Comment by Soujanya2004** [comment]
@yashksaini-coder can't VC, if u want to DM then u can have my LinkedIn
https://www.linkedin.com/in/soujanya-c-3a63a223a/

**Comment by Soujanya2004** [comment]
> > @yashksaini-coder discord is having issue sending messages so please text here
> 
> okh where can I obtain a free mapbox token

Go to mapbox websites create acc and go to access token and create new token

**Comment by yashksaini-coder** [comment]
> @yashksaini-coder btw I have shared my full .env file which has all the tokens in it ryt

okh so do one thing, can you check the changes in a seperate local project

**Comment by Meetpidev** [comment]
@Soujanya2004 CLOSE THIS pr AS THIS FEATURE IS ALREADY IMPLEMENTED BY ME..

**Comment by aslams2020** [comment]
This has been closed already

**Pull request closed without merging**
