### PR TITLE
Improving Footer UI (#469)

### LINKED ISSUE #469: [Bug]: Style Social Media Icons and Update "Wanderlust" Color Theme at footer
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The current CSS styling for the social media icons lacks visual appeal, and the color theme of "Wanderlust" could be enhanced to better align with the website’s branding. Adding proper CSS styles to the social media icons (e.g., hover effects, size adjustments, consistent color scheme) will improve aesthetics and user engagement. Additionally, updating the color theme of "Wanderlust" will help create a cohesive brand identity.

### Expected behavior

Redesigned social media icons with visually appealing styles, including hover effects and color adjustments.
A refreshed color theme for "Wanderlust" to improve brand alignment and visual consistency.
Consistent styling across all pages, ensuring that changes are responsive and accessible on all devices.

### Add ScreenShots

_No response_

### On which device are you experiencing this bug?

_No response_

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by dipexplorer**
Fixes #469

This PR focuses on improving the visual design of social media icons and updating the color theme of the "Wanderlust" footer to align with the website’s branding. It includes enhancements to the social media icons' hover effects, size adjustments, and color consistency, as well as an updated color scheme for "Wanderlust" to ensure a cohesive brand identity.

### Changes
- Styled social media icons with enhanced hover effects and size adjustments for better interactivity.
- Applied a consistent color scheme to the social media icons, matching the branding and theme.
- Updated the "Wanderlust" color theme at the footer to improve visual cohesion with the overall website design.
- Ensured that the new styles are responsive across various screen sizes and devices.

### Testing Instructions
1. Pull this branch.
2. Run `npm install` to install dependencies.
3. Run `npm test` to execute the test suite.
4. Verify that ...

### Screenshots (if applicable)

https://github.com/user-attachments/assets/a7471cd1-6077-4267-91d2-0f080b8674dd

### Checklist
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I am working on this issue under GSSOC

### CODE REVIEW

**Comment by dipexplorer** [comment]
@Soujanya2004 ,

I've put considerable effort into the footer UI update, dealing with complex CSS specificity. Could you please review and consider assigning a more appropriate level?

**Comment by Soujanya2004** [comment]
@dipexplorer

**Comment by Meetpidev** [comment]
@Soujanya2004 that red wanderlust is not looking good.. need to change it

**Comment by Meetpidev** [comment]
@Soujanya2004 PR #542 in this you gave level 1 but in the issue of it you gave level 2.. so requested to accept that level 2 not by level 1...

**Comment by Soujanya2004** [comment]
@dipexplorer conflicts

**Pull request merged**
