### PR TITLE
New list add form image preview fix along with tags styling

### LINKED ISSUE #389: [Feature Request]: Improve the image preview section in New list add form
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

As you can see in the screenshot. There is no style or spacing, margin is there when It display the added image preview. Not even recognize the individual image.

### Use Case

I add proper spacing and sizing for each image preview.

### Benefits

_No response_

### Add ScreenShots

image

@Soujanya2004  Please assign it to me.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by Suvadip-sana**
### Description
I improve the image preview styling of new list add form, along with tags styling with both dark mode and normal mode.

### Related Issues
Link any related issues using the format `Fixes #issue_number`. 
This helps to automatically close related issues when the PR is merged.
- Placeholder: "Fixes #389 "

### Screenshots (if applicable)
Add any screenshots that help explain or visualize the changes.
image
image
image

### Checklist
Make sure to check off all the items before submitting. Mark with [x] if done.
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I am working on this issue under GSSOC

### @Soujanya2004   Marge it. And don't forget to add all the labels as per ISSUE #389

### CODE REVIEW

**Comment by Suvadip-sana** [comment]
@Soujanya2004  I set the image preview style for 4 image, for both form because in my another issue for set the limitation of the number of image upload, where I am going to set the limit of 4 image.  
I think 4 image is enough.

**Comment by Meetpidev** [comment]
i already sent PR for setting tags.. #419

**Comment by Meetpidev** [comment]
> i already sent PR for setting tags.. #419

i added to select type when creating new listing.... just a frontend part..

**Comment by Suvadip-sana** [comment]
@Soujanya2004  @Meetpidev 

Here already tags feature is there for filter out the listing. So why there is need of genera feature? Is this make any sense to have both feature? I don't think so!

**Comment by Meetpidev** [comment]
both genre and tags are the same...

**Comment by Meetpidev** [comment]
i just named it genre inplace of tags.. while i was working ..

**Comment by Suvadip-sana** [comment]
> i just named it genre inplace of tags.. while i was working ..



> both genre and tags are the same...

Yes I said exactly the same. So there is no need to add `genera` functionality over `Tag` functionality. Because there is already `Tag` features there. Hope my perspective  is clear?

**Comment by Soujanya2004** [comment]
@Suvadip-sana conflicts please resolve

**Comment by Suvadip-sana** [comment]
@Soujanya2004  Solved. Marge it

**Comment by Suvadip-sana** [comment]
@Soujanya2004  Hey you missed it's labeling before marge. Please give it labeled as per ISSUE #389

**Comment by Suvadip-sana** [comment]
@Soujanya2004  Please add it otherwise it's not count on leaderboard.

**Pull request merged**
