### PR TITLE
BG-IMAGE IN LOGIN & SIGNuP PAGE

### LINKED ISSUE #480: [Bug]: add signup and login page bg
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug
image

### Expected behavior

add this bg to improve ui
and make sure its aligned with respect to the background
make the login and signup container transparent 

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by Meetpidev**
### Description
A clear and concise description of what the PR does.
  - Updates styling

### Related Issues
Fixes #480

### Screenshots 
image
image

### Checklist
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I am working on this issue under GSSOC

### CODE REVIEW

**Comment by Meetpidev** [comment]
@Soujanya2004 Review PR..

**Comment by Soujanya2004** [comment]
@Meetpidev i wanted u to add the given image as bg and then make the container transparent dont blur it

**Comment by Meetpidev** [comment]
@Soujanya2004 where is your app.js file ?

**Comment by Meetpidev** [comment]
@Soujanya2004 i can not find it.. see in repo

**Comment by Meetpidev** [comment]
@Soujanya2004 did you check ? app.js file is missing in repo..

**Comment by Meetpidev** [comment]
> @Meetpidev i wanted u to add the given image as bg and then make the container transparent dont blur it

if i do this then its not look good

**Comment by Meetpidev** [comment]
> > @Meetpidev i wanted u to add the given image as bg and then make the container transparent dont blur it
> 
> if i do this then its not look good..

**Comment by Meetpidev** [comment]
@Soujanya2004 text are not visible perfectly without giving blur effect..

**Comment by Soujanya2004** [comment]
that is y i said to align container to right

**Comment by Soujanya2004** [comment]
fine don't make the container transparent
add similar blue bg for it

**Comment by Meetpidev** [comment]
@Soujanya2004 background imge should be in entire page( with blur effect like following picture) and above that login/signup page glass effect ? right ?

**Comment by Meetpidev** [comment]
> @Soujanya2004 background imge should be in entire page( with blur effect like following picture) and above that login/signup page glass effect ? right ?

@Soujanya2004  ??

**Comment by Soujanya2004** [comment]
> @Soujanya2004 background imge should be in entire page( with blur effect like following picture) and above that login/signup page glass effect ? right ?

yes align the container to right

**Comment by Meetpidev** [comment]
@Soujanya2004 
image

You want this kind of style .. where login/signup container should be placed right.. .. tell me if im wrong.. im implementing this

**Comment by Meetpidev** [comment]
@Soujanya2004 

IS IT OKAY ??

image

**Pull request closed without merging**
