### PR TITLE
Fixed navbar to add HOME tag

### LINKED ISSUE #337: [Bug]: Home Tag In Navbar
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected behavior

 there should be option of it.. 

### Add ScreenShots

image

### On which device are you experiencing this bug?

_No response_

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by Meetpidev**
### Description
A clear and concise description of what the PR does.
- This PR does the following:
  - Updates 

### Related Issues
- "Fixes #337 "

### separate option for add listing
Screenshot 2024-11-02 163513

### Changes
List the detailed changes made in this PR.
- Fixed a bug in navbar. its check if user is admin or not if its admin only then its shows add listing option otherwise not.

### Checklist
Make sure to check off all the items before submitting. Mark with [x] if done.
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I am working on this issue under GSSOC

### CODE REVIEW

**Comment by Meetpidev** [comment]
@Soujanya2004 Requested to review PR..

**Comment by Soujanya2004** [comment]
@Meetpidev plz add necessary screenshots 
other contributor is working on the bug actually

**Comment by Meetpidev** [comment]
@Soujanya2004 Requested to review again...

**Comment by Meetpidev** [comment]
@Soujanya2004 Please Review PR

**Comment by Soujanya2004** [comment]
@Meetpidev anyone can add their property once logged in

**Comment by Meetpidev** [comment]
> @Meetpidev anyone can add their property once logged in

But that is wrong.. we have to authorized feature in website.. we must defined that which type of user access which feature..

**Comment by Meetpidev** [comment]
> @Meetpidev anyone can add their property once logged in

If so then there there is no meaning of type of admin..

**Comment by Soujanya2004** [comment]
admin feature is to just modify any listing though he/she is not the owner of the property

**Comment by Meetpidev** [comment]
> admin feature is to just modify any listing though he/she is not the owner of the property

@Soujanya2004 okay i got you..what you are trying to say... but if someone want to add property then he/she must me first sigup as admin only then they can add... this is the better way.. by it we can authorized the features...

**Comment by Soujanya2004** [comment]
> > admin feature is to just modify any listing though he/she is not the owner of the property
> 
> @Soujanya2004 okay i got you..what you are trying to say... but if someone want to add property then he/she must me first sigup as admin only then they can add... this is the better way.. by it we can authorized the features...

no, anyone who logins will hv ability to add their property, they dont have to be admin, admin role is to maintain ethics in the website, just in case anyone tries to misuse website thats it

**Comment by Meetpidev** [comment]
@Soujanya2004 Done.. i removed the admin condition... and added separate option for add properties... as i shown in screenshort...

**Comment by Soujanya2004** [comment]
@Meetpidev airbnb ur home and add ur listing does the same thing ryt

**Comment by Meetpidev** [comment]
> @Meetpidev airbnb ur home and add ur listing does the same thing ryt

@Soujanya2004  Its not same thing.. "airbnb ur home" and addlisting.. its not same..

**Comment by Soujanya2004** [comment]
@Meetpidev that is what i was trying to tell when you opened the issue

**Comment by Soujanya2004** [comment]
> > @Meetpidev airbnb ur home and add ur listing does the same thing ryt
> 
> @Soujanya2004 Its not same thing.. "airbnb ur home" and addlisting.. its not same..

how is it different can u explain

**Comment by Meetpidev** [comment]
@Soujanya2004 but there should be separate option for to redirect to home and for add listing

**Comment by Soujanya2004** [comment]
@Meetpidev for redirecting to homepage there is 'explore' link and to add new listing there is 'airbnb ur home' link

**Comment by Meetpidev** [comment]
@Soujanya2004 As i mentioned before thatm  that plane and ecplore is consider as a logo... when new user will come to it he think that its an logo.. they will find home tag to redirect homepage..

**Comment by Soujanya2004** [comment]
@Meetpidev fine?
you can just change the airbnb ur home button color to color used when its hovered
i will merge it

**Comment by Soujanya2004** [comment]
> @Soujanya2004 As i mentioned before thatm that plane and ecplore is consider as a logo... when new user will come to it he think that its an logo.. they will find home tag to redirect homepage..

fine change explore to explore listing?

**Comment by Meetpidev** [comment]
@Soujanya2004 i dont understand.. when we hover on that btn then btn must be change its backgroundColor.. right ??

**Comment by Soujanya2004** [comment]
@Meetpidev u will notice it on hovering the bg color changes to certain color, i want that color for the button, on hovering u can add box shadow or something

**Comment by Meetpidev** [comment]
> > @Soujanya2004 As i mentioned before thatm that plane and ecplore is consider as a logo... when new user will come to it he think that its an logo.. they will find home tag to redirect homepage..
> 
> fine change explore to explore listing?

Its not good to change explore -> explore listing..  Because length of the string/character increased.. doesn fir on navbar and also doesnt suitable...

**Comment by Soujanya2004** [comment]
> > > @Soujanya2004 As i mentioned before thatm that plane and ecplore is consider as a logo... when new user will come to it he think that its an logo.. they will find home tag to redirect homepage..
> > 
> > 
> > fine change explore to explore listing?
> 
> Its not good to change explore -> explore listing.. Because length of the string/character increased.. doesn fir on navbar and also doesnt suitable...

even i thought the same now

**Comment by Meetpidev** [comment]
@Soujanya2004 
### I hope you understand why we need separate option for to redirect to home and for add listing..

**Comment by Meetpidev** [comment]
@Soujanya2004 nono.. dont change...  i just changed the "airbnp ur home" -> Home , Add property -> add property form..
everything remains same..

**Comment by Soujanya2004** [comment]
just add clip of the demonstration

**Comment by Meetpidev** [comment]
@Soujanya2004 
Requested TO Review PR..
https://github.com/user-attachments/assets/2f3fdb3f-9898-4888-b070-23a27aa049f9

**Comment by Soujanya2004** [comment]
@Meetpidev as i said before can you remove add ur property link and 'airbnb ur home' , just replace 'Airbnb ur home' to Add your property'(functionality remains like original) ok, i will give you level2 no worries
rest all is fine

**Comment by Soujanya2004** [comment]
@Meetpidev i dont want you to change button redirecting, let it be same like first
instead of airbnb ur home change text to add ur property
i hope u get it

**Comment by Meetpidev** [comment]
@Soujanya2004 ITs done .. Please Review Again...

**Comment by Meetpidev** [comment]
@Soujanya2004 Requested to review again.. i changed code according to your requirements....

**Comment by Meetpidev** [comment]
@Soujanya2004 When i was working on it, i faced issue that you wrote the code in all the css randomly... 
i mean to say that if in html code if first tag is nav and othe classes you give that tag then all the style of it should be write first.. you should not do like .nav style write 1st then other styling and then again .nav styling...

**Comment by Meetpidev** [comment]
@Soujanya2004 
In style.css .. the footer style is always written in last as footer is placed last... and all the media quary should be written together....
there is very inconsistent style you wrote.. for the developer its hard to find that where the style of perticular component written ...
if you write code tag by tag like first header,nav,middle-section,footer,keyframes,mediaquary.. then its easy to find the style...

**Comment by Meetpidev** [comment]
Uploading Recording 2024-11-03 122154.mp4…

**Comment by Meetpidev** [comment]
https://github.com/user-attachments/assets/f5c78335-e8cd-41de-b0b2-2a01680354a4

**Comment by Meetpidev** [comment]
@Soujanya2004 Can i add icons for login signup logout ?? as of now there is no icons displayed... like login (icon), signUp (icon) etc...

**Comment by Soujanya2004** [comment]
> @Soujanya2004 When i was working on it, i faced issue that you wrote the code in style.css randomly... i mean to say that if in html code if first tag is nav and othe classes you give that tag then all the style of it should be write first.. you should not do like .nav style write 1st then other styling and then again .nav styling...

yeh i had arranges it well but all the contributors have changed the order

**Comment by Soujanya2004** [comment]
> @Soujanya2004 Can i add icons for login signup logout and yourprofile ?? as of now there is no icons displayed as you can see in the video ... like login (icon), signUp (icon) etc...

sure sure you can raise separate issue i will assign u

**Comment by Soujanya2004** [comment]
since there were many changes and the contributor has made the requested changes many times i have labeled level2

**Comment by Soujanya2004** [comment]
@Meetpidev you can just run init->index.js file to load listings, since its empty now

**Pull request merged**
