### PR TITLE
Design signin signup

### LINKED ISSUE #126: [Feature Request]: Feature enhancement of the sign in & sign up section in navbar.
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

For now the section where the Sign in & Sign up are displaying on navbar, It implement a logic that is the user logged in then show only 'log out' option.  If not then show 'Sign Up' & 'Sign In'

For now the format of it'd displaying style is too simple and not good at all.

Here i want to improve it's format. Like when logged in it display different avatar like 'Profile Image Avatar'  and when logged out it display different avatar.

### Use Case

I wan to wrap up all that stuff that i said above, like this -->

Uploading in.mp4…

Which is looking cool, more understandable for normal user, like modern website.

### Benefits

_No response_

### Add ScreenShots

For now it's looks like this.  Which is not good
image
image

Please assign me this task. I want to work on it. Please give high label for this as possible, It would be very appreaciated for me. Thank you. @S 

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### LINKED ISSUE #144: [Bug]: Searchbar is not responsive for mobile screen
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

As you seen in the screensort the search bar on the navbar is not responsive in mobile screen. It's expand beyond the screen.

image

### Expected behavior

It should be contained with in screen size.  need to adjust it's css for responsiveness.

### Add ScreenShots

@Soujanya2004   Please assign me this ISSUE. It's need to be fixed.

### On which device are you experiencing this bug?

_No response_

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by Suvadip-sana**
### Description
**I completed three task actually**
1) I redesign the whole `navbar` along with responsiveness. I add default avatar for when the user logged in and also for logged out. As you seen in the video. And also design the custom dropdown for displaying the `log in` & `sign up` for logged out user. And also `loge out` and go to `your profile`.  Which looks visually appealing. ISSUE #126 

2)  I build two different navbar for mobile screen and one for computer screen which fix the responsiveness problem of the navbar. As per ISSUE #126 

4)  I solve another ISSUE #144 That is for the responsive ness of the search bar for mobile screen. Which I resolved In this same PR.

- This PR does the following:
  - Fixes ... The navbar responsiveness along with the feature enhancement of displaying log in, log out section with avatar.  Also fix the mobile screen navbar along with it's responsiveness.
  - Updates ... Updates the both `mobile navbar` and `computer screen` navbar.

### Related Issues
Link any related issues using the format `Fixes #issue_number`. 
This helps to automatically close related issues when the PR is merged.
**In this PR I actually solve two ISSUE**
- Placeholder: "Fixes #126 "
- Placeholder: "Fixes #144 "

### Changes
List the detailed changes made in this PR.
- Added a new feature to ... `**Navbar sign in, log in section**`
- Refactored the ... Navbar section
- Fixed a bug in ... **Navbar**

### Screenshots (if applicable)
Add any screenshots that help explain or visualize the changes.

https://github.com/user-attachments/assets/1b89271c-504a-4b1f-ba7d-47019c744b75

https://github.com/user-attachments/assets/e36ea82e-ff9b-41f0-bb79-4a048308cf91

### Checklist
Make sure to check off all the items before submitting. Mark with [x] if done.
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I am working on this issue under GSSOC

Please give me `label-3` and `label-1` for this two ISSUE. It take effort.
### Please add `two individual points label` for solving the two ISSUE one is #126  another one is #144 

@Soujanya2004  So please don't forget this.  It's mandatory for label me up and reflect the point on `leaderboard`.

### CODE REVIEW

**Comment by Soujanya2004** [comment]
@Suvadip-sana it has conflicts please resolve

**Comment by Suvadip-sana** [comment]
@Soujanya2004 Marge it please

**Review by RadhikaMalpani1702 — COMMENTED** [review]
@MastanSayyad review this PR

**Review by MastanSayyad — COMMENTED** [review]
multiple labels are assign reducing 1

**Pull request merged**
