### PR TITLE
Give Access to Admin #132

### LINKED ISSUE #132: [Feature Request]: Give access to admin
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Admin should have access over all the listing and reviews i.e they can edit delete or add any listing
I will be sharing username and password of the admin which should be given access to entire website as owner, whenever the user is logged in with that username and password, all access should be permitted (owner of all listing created on the website)

### Use Case

Main access should be given to developer/admin in case of faulty usage of website

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by dipexplorer**
Fixes #132 

Added admin user with full access to the admin to all listings and users right now on the platform. With this feature, the admin can  delete, or view any listing or review when logged in with the provided admin credentials. 

### Changes
When logged in as an admin, the user is granted full access permissions across the site.
The admin can remove listings and users for now.
Added a “Welcome To The Admin's Dashboard” message to the navbar upon successful admin login, providing visual confirmation of admin status.

### Testing Instructions
Detailed instructions on how to test the changes. Include any setup needed and specific test cases.
1. Pull this branch.
2. Run `npm install` to install dependencies.
3. Run `npm test` to execute the test suite.
4. Verify that ...

### Screenshots (if applicable)
Screenshot (225)
Screenshot (226)

### Checklist
Make sure to check off all the items before submitting. Mark with [x] if done.
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I am working on this issue under GSSOC

### CODE REVIEW

**Comment by dipexplorer** [comment]
Hello @Soujanya2004,

For now, I have implemented access for the admin to delete listings and users, as this covers some essential functionality. I understand that there may be a need for additional features in the admin interface, so please feel free to raise individual issues for each additional requirement with proper labels.

Tomorrow is my last exam, so it's been challenging to keep up with creating detailed issues myself, so assigning them directly to me would be very helpful. I’ll prioritize these tasks as they come in and ensure each one is addressed as quickly as possible.

Thanks for your understanding and support!

**Comment by Soujanya2004** [comment]
@dipexplorer it has conflicts see once

**Comment by Soujanya2004** [comment]
> Hello @Soujanya2004,
> 
> For now, I have implemented access for the admin to delete listings and users, as this covers some essential functionality. I understand that there may be a need for additional features in the admin interface, so please feel free to raise individual issues for each additional requirement with proper labels.
> 
> Tomorrow is my last exam, so it's been challenging to keep up with creating detailed issues myself, so assigning them directly to me would be very helpful. I’ll prioritize these tasks as they come in and ensure each one is addressed as quickly as possible.
> 
> Thanks for your understanding and support!

yeh, sure sure

**Comment by dipexplorer** [comment]
> > Hello @Soujanya2004,
> > For now, I have implemented access for the admin to delete listings and users, as this covers some essential functionality. I understand that there may be a need for additional features in the admin interface, so please feel free to raise individual issues for each additional requirement with proper labels.
> > Tomorrow is my last exam, so it's been challenging to keep up with creating detailed issues myself, so assigning them directly to me would be very helpful. I’ll prioritize these tasks as they come in and ensure each one is addressed as quickly as possible.
> > Thanks for your understanding and support!
> 
> yeh, sure sure And btw my exams starts from tomorrow 😅

@Soujanya2004, 
All the best for your exam!

***Imp***
To ensure that the admin password and email are properly set up, you’ll need to run the admin.js file individually. This will save the necessary information to the database, which you can change directly according to your preference.

**Comment by Soujanya2004** [comment]
@dipexplorer i wanted admin page to be accessible to only me, if anyone can run admin.ejs then everyone will have access ryt

**Comment by Soujanya2004** [comment]
@dipexplorer you can give username and password into the database, anyone who logins in with the same username password will be able to access admin page, i will give you my credentials which should be used for admin access. u can raise another issue and work on it i will label it level3.

**Pull request merged**
