### PR TITLE
Implement CORS for Cross-Origin Resource Sharing in the Backend

### LINKED ISSUE #35: Security Patch : Implement CORS Support in Express Application
**Description:**

Our current Express application does not have Cross-Origin Resource Sharing (CORS) implemented, which may lead to issues when our frontend (hosted on a different domain/port) tries to make requests to the backend. This lack of support can restrict the accessibility of our API and hinder frontend development.

**Impact**: 

Implementing CORS will allow our frontend to communicate with the backend without restrictions, facilitating development and improving user experience.

Hey @Soujanya2004 Please assign this task to me

### PR DESCRIPTION
**Pull request by harish08102004**
##Fixed #35 

### What does this PR do?
This PR adds CORS implementation to the backend to allow cross-origin requests from the frontend. The `cors` middleware has been added globally, and the origin has been restricted to the frontend domain to ensure secure API access.

### Changes:
- Added the `cors` package.
- Applied CORS settings globally with the allowed origin set to `http://your-frontend-domain.com`.
- Enabled credentials for proper session management across domains.
- Allowed HTTP methods: GET, POST, PUT, DELETE.

### CODE REVIEW

**Comment by harish08102004** [comment]
Hey @Soujanya2004 I have raised this PR for solving CORS error. Please check it and merge,
Additionally add labels
Hacktoberfest,
Gssoc-ext,
Level

**Comment by usha-here** [comment]
@harish08102004 
Hey could you help me in how to run the project in my system ? 
I am clicking on the link of deployement but its showing issue.
image

**Comment by Soujanya2004** [comment]
@harish08102004 fyn now?

**Comment by harish08102004** [comment]
Yeah thanks mate.

**Comment by Soujanya2004** [comment]
@harish08102004 can you please help @usha-here  with the issue

**Pull request merged**
