### PR TITLE
Create Deployment link

### LINKED ISSUE #320: [Bug]: Deployment Link Not Working
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Page not found error in live link..

### Expected behavior

It should be deployed perfectly..

### Add ScreenShots
image

### On which device are you experiencing this bug?
All The Devices.. 

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by Meetpidev**
### Description
A clear and concise description of what the PR does.
- This PR does the following:
  - Updates ...

### Related Issues
- Fixes #320

### Changes
List the detailed changes made in this PR.
- Added a new deplyment(vercel) link  

### Screenshots
WhatsApp Image 2024-11-04 at 11 14 34_f7b9c0f3

### Additional Context
LINK = https://wanderlust-2024-lyart.vercel.app/

### Checklist
Make sure to check off all the items before submitting. Mark with [x] if done.
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I am working on this issue under GSSOC

### CODE REVIEW

**Comment by Meetpidev** [comment]
@Soujanya2004 Requesed to review PR..

**Comment by Meetpidev** [comment]
@Soujanya2004 
### Requested to add me in this section based on my number of commits... its matters a lot for me.. as a contributer...
image

**Comment by Soujanya2004** [comment]
> ## Merge state
> 
> Show environments
> ### This branch was successfully deployed
> 1 active deployment
> Show all checks
> ### All checks have passed
> 3 successful checks
> ### This branch has no conflicts with the base branch
> Merging can be performed automatically.
> Merge pull request
> You can also [open this in GitHub Desktop](x-github-client://openRepo/https://github.com/Soujanya2004/wanderlust-2024?branch=pr%2F371&pr=371) or view command line instructions .
> 
> [@Soujanya2004](/Soujanya2004)
> 
> 
> #### Add a comment
> Comment
> Write
> Preview
> 
> 
> Add your comment here...
> 
> [ Markdown is supported ](https://docs.github.com/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax) 
> Paste, drop, or click to add files
>  Close pull request
> Comment
> Remember, contributions to this repository should follow its [contributing guidelines](/Soujanya2004/wanderlust-2024/blob/13f7dd6ca9fde546fac4ea0cb5ae824e4926babd/Contributing.md) and [code of conduct](/Soujanya2004/wanderlust-2024/blob/13f7dd6ca9fde546fac4ea0cb5ae824e4926babd/CODE_OF_CONDUCT.md).
>  **ProTip!** Add [.patch](/Soujanya2004/wanderlust-2024/pull/371.patch) or [.diff](/Soujanya2004/wanderlust-2024/pull/371.diff) to the end of URLs for Git’s plaintext views.
> Reviewers
> No reviews
> Still in progress?
> Convert to draft
> Assignees
> No one—assign yourself
> Labels
> None yet
> Projects
> None yet
> Milestone
> No milestone
> Development
> Successfully merging this pull request may close these issues.
> 
> [ [Bug]: Deployment Link Not Working ](https://github.com/Soujanya2004/wanderlust-2024/issues/320)
> 
> Notifications
> Customize
> 
> Unsubscribe
> You’re receiving notifications because you’re watching this repository.
> 
> 1 participant
> [ @Meetpidev ](/Meetpidev)
>  Maintainers are allowed to edit this pull request.
>  **Lock conversation**

@Meetpidev i will dont worry

**Comment by Soujanya2004** [comment]
Screenshot (259)
@Meetpidev fine?

**Pull request merged**
