### PR TITLE
back to prev

### PR DESCRIPTION
**Pull request by shar2710**
### Description
A clear and concise description of what the PR does.
- This PR does the following:
  - Adds ... back to prev button
  - Fixes ... #383 
  - Updates ...

### Related Issues
Link any related issues using the format `Fixes #issue_number`. 
This helps to automatically close related issues when the PR is merged.
- Placeholder:

### Changes
List the detailed changes made in this PR.
- Added a new feature to ...
- Refactored the ...
- Fixed a bug in ...

### Testing Instructions
Detailed instructions on how to test the changes. Include any setup needed and specific test cases.
1. Pull this branch.
2. Run `npm install` to install dependencies.
3. Run `npm test` to execute the test suite.
4. Verify that ...

### Screenshots (if applicable)
Add any screenshots that help explain or visualize the changes.

### Additional Context
Any additional context or information that reviewers should be aware of.
- This PR is based on the following...

### Checklist
Make sure to check off all the items before submitting. Mark with [x] if done.
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I am working on this issue under GSSOC

### CODE REVIEW

**Comment by Soujanya2004** [comment]
@shar2710 you have changes 5000 files??
please check if u have pushed node modules 
review again

**Comment by shar2710** [comment]
please check now @Soujanya2004

**Comment by Soujanya2004** [comment]
@shar2710 the deployed link if not working effeciently, toggle is not working and show listing page is loading forever
so can u revert the changes u made

**Comment by Soujanya2004** [comment]
@shar2710 as soon as possible

**Comment by Suvadip-sana** [comment]
@Soujanya2004    All the changes she made create problem. After eliminate this changes the server work fine. Is this actually tested in locally? She not even attached her test video recording.🤣

@Soujanya2004  You should check this type of things before marge.

**Comment by Suvadip-sana** [comment]
@Soujanya2004  So all ok. I will create a PR for this.

**Pull request merged**
