### PR TITLE
ADDED GENRE FEATURE

### LINKED ISSUE #338: [Feature Request]: What type of listing is ?
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Use Case

By adding what type of listing is added, after that we can easly extrect that listing by type...

### Benefits

we can easly extrect that listing by type... by doing this that open place below navbar is working...

### Add ScreenShots

_No response_

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by Meetpidev**
### Description
- This PR does the following:
  - Updates in to create new listing..

### Related Issues
- Fixes #338 

### Changes
- Added a new feature to creating listing

### DEMO:
https://github.com/user-attachments/assets/2d85f77e-e229-40cb-bba5-63069d9727cf

### Checklist
Make sure to check off all the items before submitting. Mark with [x] if done.
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I am working on this issue under GSSOC

### CODE REVIEW

**Comment by Meetpidev** [comment]
@Soujanya2004 Requested to review PR...

**Comment by Soujanya2004** [comment]
@Meetpidev u have added all 5 commits?

**Comment by Soujanya2004** [comment]
@Meetpidev problem is i dont have access to edit all listing
some of the users have created it and only they can add it

**Comment by Meetpidev** [comment]
> @Meetpidev problem is i dont have access to edit all listing some of the users have created it and only they can add it

simply delete that listing..

**Comment by Meetpidev** [comment]
> @Meetpidev u have added all 5 commits?

yes

**Comment by Meetpidev** [comment]
@Soujanya2004 Make sure that in website and in repo you arrange contributers based on no. of PRs./no. of commits..

**Comment by Soujanya2004** [comment]
@Meetpidev i will keep this on hold for the moment bcz i am a bit occupied with other works so , i will review it in few days

**Comment by Meetpidev** [comment]
@Soujanya2004 did you merged another pr for this functionality ??

**Comment by Meetpidev** [comment]
@Soujanya2004 you said that you are holding this functionality... then why you accept another pr that have the same feature as this PR

**Comment by Meetpidev** [comment]
@Soujanya2004 WHAT ABOUT THIS ?

**Comment by Soujanya2004** [comment]
@Meetpidev conflicts

**Pull request closed without merging**
