### PR TITLE
Bookings page added

### LINKED ISSUE #206: [Feature Request]: add booking functionality
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

user will be able to book site
options include no. of nights spending, check-in date and time etc.
no other user can book the same site while the user stay is not completed.

### Use Case

feature addition of website

### Benefits

_No response_

### Add ScreenShots

_No response_

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by NK-Works**
### Description
A clear and concise description of what the PR does.
- This PR does the following:
  - Adds bookings page
  - Fixes #206
  - Updates show.ejs and creates booking.ejs

### Related Issues
Link any related issues using the format `Fixes #issue_number`. 
This helps to automatically close related issues when the PR is merged.
- Placeholder: "Fixes #206".

Video:
https://github.com/user-attachments/assets/9fed19f7-1cc5-49da-a29f-1f29040fa00c

### Checklist
Make sure to check off all the items before submitting. Mark with [x] if done.
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I am working on this issue under GSSOC

### CODE REVIEW

**Comment by Soujanya2004** [comment]
@NK-Works conflicts

**Comment by NK-Works** [comment]
Resolved

**Comment by NK-Works** [comment]
Please assign the lavel label or else it won't be counted

**Comment by NK-Works** [comment]
@Soujanya2004 please assign labels 🙏

**Comment by NK-Works** [comment]
No biggie thanks :)

**Pull request merged**
