### PR TITLE
ADDED LIKE/DISLIKE FEATURE..

### LINKED ISSUE #478: [Feature Request]: LISTING LIKE FEATURE
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

THERE SHOULD BE FEATURE TO LIKE LISTING

### Use Case

BENIFITS TO FIND BEST LISTINGS

### Benefits

BENIFITS TO FIND BEST LISTINGS

### Add ScreenShots

_No response_

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by Meetpidev**
### Description
A clear and concise description of what the PR does.
  - Updates like & dislike feature..

### Related Issues
Fixes #478 

### Changes
- Added a new feature to listungs..

###  DEMO
https://github.com/user-attachments/assets/fc7b61e4-d224-4e5c-bae9-2ff15a5cf27d

### Checklist
Make sure to check off all the items before submitting. Mark with [x] if done.
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I am working on this issue under GSSOC

### CODE REVIEW

**Comment by Meetpidev** [comment]
@Soujanya2004 Please Review PR...

**Comment by Soujanya2004** [comment]
@Meetpidev
user can like listing on show listing page and the user can just view the number of likes on homepage on each listing

**Comment by Soujanya2004** [comment]
@Meetpidev and after each like make sure there is an animation for better UI 
i will label level3 no worries

**Comment by Meetpidev** [comment]
@Soujanya2004 in previous PR #488.. in that the same code as my.... reset link is send to the user email... user can reset... can not know that what they set pass.. before....
image

**Comment by Meetpidev** [comment]
> @Meetpidev user can like listing on show listing page and the user can just view the number of likes on homepage on each listing

it is done.. see in the video..

**Comment by Soujanya2004** [comment]
> > @Meetpidev user can like listing on show listing page and the user can just view the number of likes on homepage on each listing
> 
> it is done.. see in the video..

ohk i got confused, add animations na

**Comment by Meetpidev** [comment]
@Soujanya2004 You forgot to label it.. please label th pr...

**Comment by Meetpidev** [comment]
@Soujanya2004 An please Review PR perfectly.. because people just sent PR because of POINTS.. as gssoc is around to close

**Comment by Soujanya2004** [comment]
sorry forgot!

**Comment by Meetpidev** [comment]
@Soujanya2004 please recheck the functionally of reset & update password as well.. it must be dont effect by previous PR.. please tell me if there is an error

**Comment by Soujanya2004** [comment]
@Meetpidev its working fine

**Pull request merged**
