### PR TITLE
#33 (Issue) Layout of Listing Page

### PR DESCRIPTION
**Pull request by Asjdnnc**
Fixed the design of leave a review and All reviews section

### CODE REVIEW

**Comment by aqueefcs** [comment]
Hey @Asjdnnc can squash your 3 commits into 1 commit. Its always best practice to have 1 single commit.

**Comment by Asjdnnc** [comment]
> Hey @Asjdnnc can squash your 3 commits into 1 commit. Its always best practice to have 1 single commit.

Thank you for you suggestion but now it is difficult for me to change the commits again.
Note : I only changes some code in show.ejs file

**Comment by Soujanya2004** [comment]
@Asjdnnc this pr has conflicts please resolve

**Comment by Asjdnnc** [comment]
@Soujanya2004 pls check now

**Comment by Soujanya2004** [comment]
@Asjdnnc it's still having conflicts 🙂 check app.js

**Pull request closed without merging**
