### PR TITLE
Landing page routing update

### LINKED ISSUE #410: [Feature Request]: Problem in landing page. No route work
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

In landing page all the field that supposed to be linked with existing route your back end have. But no route is added. Every route say `No page found`

You can verify that in attached video.

### Use Case

I would fix that ISSUE, in all over your landing page.
I add all possible link that need in landing page.

@Soujanya2004  Assign it to me.

### Benefits

_No response_

### Add ScreenShots

https://github.com/user-attachments/assets/438302ea-e9d5-437b-a1ce-9a258321a944

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by dev129**
Hi @Soujanya2004 
### Description
A clear and concise description of what the PR does.
- This PR does the following:
  - Updates the landing page to include actual routes for navigation.
  - Fixes any broken or placeholder links in the landing page.
  - Enhances the user interface for better navigation and usability.

### Related Issues
Link any related issues using the format `Fixes #issue_number`.
- Fixes #410 

### Changes
List the detailed changes made in this PR.
- Updated navigation routes on the landing page to link to the corresponding pages.
- Ensured all links point to valid pages within the application.
- Refactored the navigation code for better maintainability and clarity.
- Improved styling for the navigation items to enhance user experience.

### Screenshots (if applicable)
Add any screenshots that help explain or visualize the changes.

https://github.com/user-attachments/assets/1fd9a55d-1c93-4586-af48-23e0647d8792

### Additional Context
Any additional context or information that reviewers should be aware of.
- This PR is based on a recent review of the landing page structure to ensure navigation routes align with the current site structure.
- Adjustments were made to match new routes added to the project since the last update.

### Checklist
Make sure to check off all the items before submitting. Mark with [x] if done.
- [x] I have performed a self-review of my code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generate no new warnings.
- [x] I am working on this issue under GSSOC.

### CODE REVIEW

**Comment by Soujanya2004** [comment]
@dev129 screen recording u have inserted is broken please check
add screenshots atleast

**Comment by dev129** [comment]
@Soujanya2004 , I don't know hwy its broken everytime i record but here are the screenshots , which i think are necessary 
This is the dekstop view:
image

this is the footer you wished:
image

this is the listing page which users can see when they click ''start exploring'' on landing page  for including what all places are avaliable , the prices are not included so that it can be done during checkout , what many booking sites like MMT, Yatri and many sites follow: 
image

This is the sign up page which comes when we click on sign up now button below the landing page 
image

Mobile view:
image

image

If you still need anything else, let me know.

**Comment by Soujanya2004** [comment]
@dev129 great job dude

**Comment by Soujanya2004** [comment]
@dev129 why the listing display is changed
i want u to add only landing page and necessary routes for buttons
there is completely different homepage

**Comment by Soujanya2004** [comment]
@dev129 i have a suggestion 
Why don't you try to add pop up card stating 'welcome to Wanderlust...signup for better experience' and a nice bg for that just after few seconds of visiting the website
I hope u are getting what I am trying to say

**Comment by Soujanya2004** [comment]
U see it ryt in websites where user is asked to login or signup after entering a website

**Pull request merged**
