### PR TITLE
FIX NAVBAR STYLE

### LINKED ISSUE #514: [Bug]: HOMEPAGE NAVBAR STYLE
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

FIX STYLING OF NAVBAR IN HOMEPAGE

### Expected behavior

FIX STYLING OF NAVBAR IN HOMEPAGE

### Add ScreenShots

image

### On which device are you experiencing this bug?

_No response_

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by Meetpidev**
### Description
- This PR does the following:
  - Updates NAVBAR

### Related Issues
Fixes #514 

### Changes
- Fixed STYLING

### Screenshots (if applicable)
https://github.com/user-attachments/assets/2cba1784-c91e-470b-89ec-52535faa745f

### Checklist
Make sure to check off all the items before submitting. Mark with [x] if done.
- [X ] I have performed a self-review of my code
- [X ] I have commented my code, particularly in hard-to-understand areas
- [X ] My changes generate no new warnings
- [X ] I am working on this issue under GSSOC

### CODE REVIEW

**Comment by Meetpidev** [comment]
@Soujanya2004 Please Review PR..

**Comment by Soujanya2004** [comment]
@Meetpidev i dont want bright red color for hover

**Comment by Meetpidev** [comment]
> @Meetpidev i dont want bright red color for hover let it be like before light colored hover effect

its done

**Comment by Meetpidev** [comment]
i set #FF5A5F color..in hover.. that is light red color..

**Comment by Meetpidev** [comment]
@Soujanya2004 Review pr again

**Pull request merged**
