### PR TITLE
Feat: Adding ContactUs Backend functionality using Nodemailer

### LINKED ISSUE #272: [Feature Request]: ContactUs page with backend
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

There is no contactus page there is no way to connect with user i want to implement contact us page with backend functionality using nodemailer. 

### Use Case

It increases the attraction of user towards wanderlust. 

### Benefits

User can directly interact with you via mail which is also a professional way to connect. 

User can directly ask any query with you. 

### Add ScreenShots

_No response_

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by harshbhar0629**
### Description
A clear and concise description of what the PR does.
- This PR does the following:
  - Adds: Provide ContactUs functionality for user now user can directly ask any query to you.
  - Fixes #272 
  - Close #272 

### Changes
List the detailed changes made in this PR.
- Added a new feature to ContactUs Backend functionality using nodemailer

### Testing Instructions
Your executable or run command of this project remains same:)

**TESTING**

https://github.com/user-attachments/assets/902120f8-c7a3-4513-ac1c-004f137a304e

### Checklist
Make sure to check off all the items before submitting. Mark with [x] if done.
- [X] I have performed a self-review of my code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] My changes generate no new warnings
- [X] I am working on this issue under GSSOC

Code Changes:)
- app.get render the **contact form** and app.post will recieve the data and call to **contactUsController**

setup

- UI contactUs

UI

**contactUsController** It fetch data and call to **mailSender** using try and catch block for error handling

mailSender

maiSender function -> It create transporter of nodemailer by passing 
host: process.env.MAIL_HOST,
auth: {
user: process.env.MAIL_USER,
pass: process.env.MAIL_PASS,
}, and then send mail

nodemailer

Format of mail:)

mailRecieveFormat

### CODE REVIEW

**Comment by harshbhar0629** [comment]
@Soujanya2004 Please review my PR and merge it with **level-3**.

**Comment by Suvadip-sana** [comment]
@harshbhar0629 

I think you missed one file or something?
Because in this section it show this error. When I start local server.
image


Here you import it and this file is not exist in code file.  
image

@harshbhar0629 
@Soujanya2004 
Please verify it. Other wise it is difficult to run the server.

**Comment by harshbhar0629** [comment]
Ok i will add wait a minute

**Comment by Soujanya2004** [comment]
> @harshbhar0629
> 
> I think you missed one file or something? Because in this section it show this error. When I start local server. image
> 
> Here you import it and this file is not exist in code file. image
> 
> @harshbhar0629 @Soujanya2004 Please verify it. Other wise it is difficult to run the server.

Solved check one @Suvadip-sana

**Comment by Suvadip-sana** [comment]
> > @harshbhar0629
> > I think you missed one file or something? Because in this section it show this error. When I start local server. image
> > Here you import it and this file is not exist in code file. image
> > @harshbhar0629 @Soujanya2004 Please verify it. Other wise it is difficult to run the server.
> 
> Solved check once @Suvadip-sana



@Soujanya2004   

It works well. But there was no way to navigate into this page I think he missed it. I add this page link in navbar contact us option. Not major ISSUE 👍.

**Just you only add the required environment variable with your .env file for this workflow.**

**Comment by harshbhar0629** [comment]
> > > @harshbhar0629
> > > I think you missed one file or something? Because in this section it show this error. When I start local server. image
> > > Here you import it and this file is not exist in code file. image
> > > @harshbhar0629 @Soujanya2004 Please verify it. Other wise it is difficult to run the server.
> > 
> > 
> > Solved check once @Suvadip-sana
> 
> @Soujanya2004
> 
> It works well. But there was no way to navigate into this page I think he missed it. I add this page link in navbar contact us option. Not major ISSUE 👍.
> 
> **Just you only add the required environment variable with your .env file for this workflow.**

You can navigate to this page via navbar see my video of testing i also navigate to this page via navbar

**Comment by Suvadip-sana** [comment]
> > > > @harshbhar0629
> > > > I think you missed one file or something? Because in this section it show this error. When I start local server. image
> > > > Here you import it and this file is not exist in code file. image
> > > > @harshbhar0629 @Soujanya2004 Please verify it. Other wise it is difficult to run the server.
> > > 
> > > 
> > > Solved check once @Suvadip-sana
> > 
> > 
> > @Soujanya2004
> > It works well. But there was no way to navigate into this page I think he missed it. I add this page link in navbar contact us option. Not major ISSUE 👍.
> > **Just you only add the required environment variable with your .env file for this workflow.**
> 
> You can navigate to this page via navbar see my video of testing i also navigate to this page via navbar




@harshbhar0629 Yes your video have. But I think by mistake you missed to push `navbar.ejs` changes.  See it her original repo and there is old path reflected. 
image

See don't worry. It's not the major ISSUE. Can be fixed.

**Comment by harshbhar0629** [comment]
> > > > > @harshbhar0629
> > > > > I think you missed one file or something? Because in this section it show this error. When I start local server. image
> > > > > Here you import it and this file is not exist in code file. image
> > > > > @harshbhar0629 @Soujanya2004 Please verify it. Other wise it is difficult to run the server.
> > > > 
> > > > 
> > > > Solved check once @Suvadip-sana
> > > 
> > > 
> > > @Soujanya2004
> > > It works well. But there was no way to navigate into this page I think he missed it. I add this page link in navbar contact us option. Not major ISSUE 👍.
> > > **Just you only add the required environment variable with your .env file for this workflow.**
> > 
> > 
> > You can navigate to this page via navbar see my video of testing i also navigate to this page via navbar
> 
> @harshbhar0629 Yes your video have. But I think by mistake you missed to push `navbar.ejs` changes. See it her original repo and there is old path reflected. image
> 
> See don't worry. It's not the major ISSUE. Can be fixed.

Sorry my bad actually problem is . Git ignore not working that's why these minor issue are coming.

**Comment by Soujanya2004** [comment]
@harshbhar0629 the changes you made is not deployed, i received mail deployment failed can you look into it

**Pull request merged**
