### PR TITLE
Adding dark mode on the Show Listing page

### LINKED ISSUE #141: [Bug]: Implement Dark Mode for Show Listing Page
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The Show Listing page does not change to dark mode when enabled.

### Expected behavior

The Show Listing page should switch to a dark theme with appropriate color adjustments for displayed content and UI elements.

### Add ScreenShots

_No response_

### On which device are you experiencing this bug?

_No response_

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by dipexplorer**
Fixes #141

Adding dark mode for the Show Listing page.

### Changes
Dark background for the page content.
Adjustments for buttons, links, and input fields to maintain contrast.

### Checklist

- [ ]  I have tested the Show Listing page in both dark and light modes.
- [ ]  The dark mode styles are consistent with the site's overall theme.
- [ ]  No new console errors or warnings were introduced during testing.

### CODE REVIEW

**Review by RadhikaMalpani1702 — COMMENTED** [review]
@mastansayyad review this PR

**Comment by Soujanya2004** [comment]
@RadhikaMalpani1702 can i know why 

> @MastanSayyad review this PR

**Comment by Soujanya2004** [comment]
> @MastanSayyad review this PR

can i know the reason

**Review by MastanSayyad — COMMENTED** [review]
Dark mode CSS changes, I'll leave this as level 2 but if similar changes found then I need to reduce it.

**Pull request merged**
