### PR TITLE
completed

### PR DESCRIPTION
**Pull request by poojabagodi**
### Description
A clear and concise description of what the PR does.
- This PR does the following:
  - Adds ...
  - Fixes ...
  - Updates ...

### Related Issues
Link any related issues using the format `Fixes #issue_number`. 
This helps to automatically close related issues when the PR is merged.
- Placeholder: "Fixes #123"

### Changes
List the detailed changes made in this PR.
- Added a new feature to ...
- Refactored the ...
- Fixed a bug in ...

### Testing Instructions
Detailed instructions on how to test the changes. Include any setup needed and specific test cases.
1. Pull this branch.
2. Run `npm install` to install dependencies.
3. Run `npm test` to execute the test suite.
4. Verify that ...

### Screenshots (if applicable)
Add any screenshots that help explain or visualize the changes.

### Additional Context
Any additional context or information that reviewers should be aware of.
- This PR is based on the following...

### Checklist
Make sure to check off all the items before submitting. Mark with [x] if done.
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I am working on this issue under GSSOC

### CODE REVIEW

**Comment by MastanSayyad** [comment]
@Soujanya2004 Any reasons you added multiple labels of levels on single PR for such minor changes which should not even have level 1? Kindly explain and add me as a collaborator as soon as possible in your repository!

image

There are a lot of spam in your project

**Comment by Soujanya2004** [comment]
@MastanSayyad i am really sorry for the confusion, i had merged it by mistake, the labels were for 3 different issues
and for as you mentioned 'there are lot of spam in your project' can you specify

**Comment by MastanSayyad** [comment]
@Soujanya2004 Like this PR it only had few minor changes still it got level 1,2,3 labels please know that one PR can have only one level label no matter how many issues it fixes

And even if you revert the PR that count as a seprate PR and the scores on this PR will get counted in the leaderboard no matter what if the labels are on the PR then score will be added

I have seen other PRs too which has multiple labels. some contributors were complaining saying it was unfair and they question on the quality of this program, so kindly please review the code before merging it

thank you

**Comment by Soujanya2004** [comment]
@MastanSayyad I had no idea we can't add multiple level, contributors asked for adding multiple level bcz they had multiple issues solved, I will make sure there are no 2 labels for single pr. And sorry for that.
Thankyou

**Pull request merged**
