### PR TITLE
FORGOT PASSWORD FEATURE..

### LINKED ISSUE #360: [Feature Request]: FORGOT PASSWORD
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

ADD FORGOT PASSWORD

### Use Case

WHAT IF WE FORGOT THE PASSSWORD THAT SET BEFORE ?

### Benefits

BY THIS FEATURE WE CAN KNOW OUR PASSWORD..

### Add ScreenShots

_No response_

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by Meetpidev**
### Description
- This PR does the following:
  - Updates Forgot Password..

### Related Issues
- Fixes #360 

### Changes
- Added a new feature: forgot passsword

### DEMO
https://github.com/user-attachments/assets/a90fa0eb-6b49-4f7c-acae-7e6c3ca5bd05

### Additional Context
NOTE: FIRST YOU HAVE TO INSTAL CRYPTO BY "npm install crypto".. THEN ITS WORK..

### Checklist
Make sure to check off all the items before submitting. Mark with [x] if done.
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I am working on this issue under GSSOC

### CODE REVIEW

**Comment by Meetpidev** [comment]
@Soujanya2004 Requested to review PR....

**Comment by Soujanya2004** [comment]
@Meetpidev i will give the mail and passkey add it then i will merge at once

**Comment by Meetpidev** [comment]
@Soujanya2004 dont need to gimme that things.. you can include by yourself in env file.. after merged...

**Comment by Meetpidev** [comment]
@Soujanya2004 Dont forget to includes that bothe the things in env file.. and also install crypto by npm i crypto.. otherwise its not worked

**Pull request merged**
