### PR TITLE
CUSTOM SCROLL-BAR

### LINKED ISSUE #502: [Feature Request]: SCROLLBAR STYLE
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

 ADD SCROLLBAR STYLE(CUSTOM COLORS) AND IT SHOULD BE SMOOTH TO SCROLL

### Use Case

 SCROLLBAR STYLE

### Benefits

ATTRECTIVE

### Add ScreenShots

image

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by Meetpidev**
### Description
- This PR does the following:
  - Updates SCROLLBAR

### Related Issues
Fixes #502 

### Changes
- Added a new feature to scrollbar

### DEMO
https://github.com/user-attachments/assets/11e53e28-71ae-4991-ac79-d8f1244c6d40

### Checklist
- [x ] I have performed a self-review of my code
- [x ] I have commented my code, particularly in hard-to-understand areas
- [x ] My changes generate no new warnings
- [x ] I am working on this issue under GSSOC

### CODE REVIEW

**Comment by Meetpidev** [comment]
@Soujanya2004 Review PR..

**Comment by Soujanya2004** [comment]
let it be just red dont add hover color

**Comment by Meetpidev** [comment]
> let it be just red dont add hover color

want to change background black ? or white  or anyother color ??

**Comment by Meetpidev** [comment]
@Soujanya2004 Chnaged based on your requirement

**Comment by Meetpidev** [comment]
@Soujanya2004 please review Pr.. i changed the color that you give me

**Pull request merged**
